apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
    providers:
      - secretbox:
          keys:
            - name: key1
              secret: <encryption-key>
      - identity: {} # can remove after at-rest encryption is confirmed
