apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
    providers:
      - secretbox:
          keys:
            - name: key1
              secret: exslobpOOc2X8IO0HICemg0cmNsFRrSIaxZiq/7GVTM=
      - identity: {} # this fallback allows reading unencrypted secrets;
