apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv0
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/db0
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv1
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/db1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv2
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/db2
  persistentVolumeReclaimPolicy: Retain
  # nodeAffinity:
    # required:
      # nodeSelectorTerms:
      # - matchExpressions:
        # - key: kubernetes.io/hostname
          # operator: In
          # values:
          # - <your-node-name>
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer